server:
  port: 80
spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/fuzzy?characterEncoding=utf-8&charset=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 1234

